name: release
on: [workflow_dispatch]
env:
  GH_USER: ${{secrets.GH_USER}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  release:
    env:
      GH_USER: '${{secrets.GH_USER}}'
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - run: echo ${{secrets.GH_USER}}
      - run: echo $GH_USER
      - run: mvn echo:echo
      - run: mvn -B -X release:prepare