name: release
on:
  workflow_dispatch:
jobs:
  env:
    GH_USER: ${{secrets.GH_USER}}
    GH_TOKEN: ${{secrets.GH_TOKEN}}
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn -B -X release:prepare